# Exported from:        http://MacBookPro16.local:5516/
# Release version:      23.3.0-beta.1
# Date created:         Tue Jun 20 09:59:14 AEST 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_ABCTemplate.yaml
