# Exported from:        http://MacBookPro16.local:5516/
# Release version:      23.3.0-beta.1
# Date created:         Tue Jun 20 09:59:14 AEST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ApplicationSecurity
spec:
- template: ABCTemplate
  scheduledStartDate: 2023-06-20T09:00:00+10:00
  phases:
  - phase: New Phase
    tasks:
    - name: Wait for Dependencies
      type: xlrelease.GateTask
    - name: Create OPA Policy
      type: opa.CreatePolicy
    - name: Build Package
      type: jenkins.Build
    - name: Check Build for Policy Compliance
      type: opa.EvaluatePolicy
    - name: Ready for QA
      type: xlrelease.GateTask
  riskProfile: Default risk profile
